# Generated by Django 4.2.28 on 2026-02-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Lần cuối hoạt động')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Hoạt động người dùng',
                'verbose_name_plural': 'Hoạt động người dùng',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('resource_approved', 'Tài liệu được duyệt'), ('resource_rejected', 'Tài liệu bị từ chối'), ('new_comment', 'Bình luận mới'), ('new_pending', 'Tài liệu chờ duyệt')], max_length=20, verbose_name='Loại thông báo')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('message', models.TextField(blank=True, verbose_name='Nội dung')),
                ('link', models.CharField(blank=True, help_text='URL để chuyển đến khi click thông báo', max_length=500, verbose_name='Đường dẫn')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_notif_recipient_unread'), models.Index(fields=['recipient', '-created_at'], name='idx_notif_recipient_created')],
            },
        ),
    ]
