# Generated by Django 4.2.28 on 2026-02-23 03:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, help_text='Mô tả tóm tắt nội dung tài liệu', verbose_name='Mô tả ngắn')),
                ('content', models.TextField(blank=True, help_text='Nội dung đầy đủ hoặc ghi chú về tài liệu', verbose_name='Nội dung chi tiết')),
                ('resource_type', models.CharField(choices=[('document', 'Tài liệu'), ('video', 'Video'), ('presentation', 'Bài trình bày'), ('exercise', 'Bài tập'), ('other', 'Khác')], default='document', max_length=20, verbose_name='Loại tài liệu')),
                ('file', models.FileField(blank=True, help_text='Cho phép: PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX, ZIP, RAR (tối đa 10MB)', null=True, upload_to='resources/files/%Y/%m/', verbose_name='Tệp đính kèm')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cho phép: JPG, PNG, GIF, WEBP (tối đa 10MB)', null=True, upload_to='resources/thumbnails/%Y/%m/', verbose_name='Ảnh thu nhỏ')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Lý do từ chối')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tải xuống')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Tác giả')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='categories.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], max_length=10, verbose_name='Trạng thái cũ')),
                ('new_status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối')], max_length=10, verbose_name='Trạng thái mới')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_logs', to='resources.resource', verbose_name='Tài liệu')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
            ],
            options={
                'verbose_name': 'Nhật ký duyệt',
                'verbose_name_plural': 'Nhật ký duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá (1-5 sao)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource', verbose_name='Tài liệu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Người bình luận')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['-created_at'],
            },
        ),
    ]
