# Generated by Django 4.2.28 on 2026-02-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['resource', '-created_at'], name='idx_comment_resource_created'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', '-created_at'], name='idx_resource_status_created'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', '-view_count'], name='idx_resource_status_views'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['status', '-download_count'], name='idx_resource_status_downloads'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', 'status'], name='idx_resource_category_status'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['author', '-created_at'], name='idx_resource_author_created'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['slug'], name='idx_resource_slug'),
        ),
        migrations.AddIndex(
            model_name='submissionlog',
            index=models.Index(fields=['resource', '-created_at'], name='idx_log_resource_created'),
        ),
    ]
